MotoStore/ViewModels/Account/LayoutViewModel.cs
using System.Collections.Generic;
using MotoStore.ViewModels.Order;
using MotoStore.ViewModels.Positions;

namespace MotoStore.ViewModels.Account
{
    public class LayoutViewModel
    {
        public RegisterViewModel RegisterViewModel { get; set; }
        public LoginViewModel LoginViewModel { get; set; }
        public AllPositionsViewModel AllPositionsViewModel { get; set; }
        public CreatePositionViewModel CreatePositionViewModel { get; set; }
        public OrderCreateViewModel OrderCreateViewModel { get; set; }
        public List<OrderViewModel> OrderViewModels { get; set; }
    }
}

MotoStore/ViewModels/Layout/LayoutViewModel.cs
using System.Collections.Generic;
using MotoStore.Models;
using MotoStore.ViewModels.Account;
using MotoStore.ViewModels.Order;
using MotoStore.ViewModels.Positions;
using MotoStore.ViewModels.UsersPersonalArea;

namespace MotoStore.ViewModels.Layout
{
    public class LayoutViewModel
    {
        public RegisterViewModel RegisterViewModel { get; set; }
        public LoginViewModel LoginViewModel { get; set; }
        public AllPositionsViewModel AllPositionsViewModel { get; set; }
        public CreatePositionViewModel CreatePositionViewModel { get; set; }
        public OrderCreateViewModel OrderCreateViewModel { get; set; }
        public List<OrderViewModel> OrderViewModels { get; set; }
        public List<User> Users { get; set; }
        public LiveOrderViewModel LiveOrderViewModel { get; set; }
        public ReportViewModel ReportViewModel { get; set; }
        public MessageViewModel MessageViewModel { get; set; }
        public List<UsersPersonalAreaViewModel> ManagerPersonalAreaUsers { get; set; }
    }
}

MotoStore/Controllers/ManagerPersonalAreaController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MotoStore.MapConfigurations;
using MotoStore.Services.Abstractions;
using MotoStore.ViewModels.Layout;
using MotoStore.ViewModels.UsersPersonalArea;
using static MoreLinq.Extensions.LagExtension;
using static MoreLinq.Extensions.LeadExtension;

namespace MotoStore.Controllers
{
    [Authorize(Roles = "Manager")]
    public class ManagerPersonalAreaController : Controller
    {
        private readonly IManagerPersonalAreService _managerPersonalAreaService;
        private readonly IOrderService _orderService;

        public ManagerPersonalAreaController(IManagerPersonalAreService managerPersonalAreaService, IOrderService orderService)
        {
            _managerPersonalAreaService = managerPersonalAreaService;
            _orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = await _managerPersonalAreaService.GetAllUsersInRoleAsync();
            
            LayoutViewModel layoutViewModel = new LayoutViewModel
            {
                ManagerPersonalAreaUsers = users.MapToUsersPersonalAreaViewModels()
            };
            layoutViewModel.ManagerPersonalAreaUsers.ForEach(u =>
            {
                u.OrdersCount = _orderService.GetOrdersByUserId(u.Id).Count();
            });
            
            return View(layoutViewModel);
        }

        [HttpGet]
        public IActionResult UserOrders(string userId)
        {
            var orders = _orderService.GetOrdersByUserId(userId);
            LayoutViewModel layoutViewModel = new LayoutViewModel
            {
                OrderViewModels = orders.MapToOrderViewModels()
            };
            return View(layoutViewModel);
        }
    }
}

MotoStore/Controllers/UserPersonalAreaController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MotoStore.MapConfigurations;
using MotoStore.Models;
using MotoStore.Services.Abstractions;
using MotoStore.ViewModels.Layout;

namespace MotoStore.Controllers
{
    [Authorize(Roles = "User")]
    public class UserPersonalAreaController : Controller
    {
        private readonly IOrderService _orderService;

        public UserPersonalAreaController(
            IOrderService orderService)
        {
            _orderService = orderService;
        }

        [HttpGet]
        public IActionResult Index(string userId)
        {
            IEnumerable<Order> orders = _orderService.GetOrdersByUserId(userId);
            LayoutViewModel layoutViewModel = new LayoutViewModel
            {
                OrderViewModels = orders.MapToOrderViewModels().ToList()
            };
            return View(layoutViewModel);
        }
    }
}

MotoStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using MotoStore.Enums
@model MotoStore.ViewModels.Layout.LayoutViewModel;
@inject UserManager<User> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MotoStore</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/reset.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<div id="spinner">
    Loading...
</div>
<header class="fixed-top">
    @{
        User user = await _userManager.GetUserAsync(User);
    }
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="bi bi-bicycle text-warning logo"></i>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Position" asp-action="All">Мотоциклы</a>
                    </li>
                    @if (@User.IsInRole(Roles.Manager.ToString()))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Position" asp-action="Add">Добавить позицию</a>
                        </li>
                    }
                </ul>
            </div>
            @if (User.Identity!.IsAuthenticated!)
            {
                <div class="dropdown">
                    <a href="#" class="d-flex align-items-center" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="nav-link corporate-color">@User.Identity.Name</i>
                        <img class="rounded-circle avatar" src="~/@user.PathToAvatar" alt="аватар">
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        @if (User.IsInRole("User"))
                        {
                            <li>
                                <a class="nav-link text-dark"
                                   asp-controller="UserPersonalArea"
                                   asp-action="Index"
                                   asp-route-userId="@_userManager.GetUserId(User)">
                                    Личный кабинет
                                </a>
                            </li>
                        }
                        else if (User.IsInRole("Manager"))
                        {
                            <li>
                                <a class="nav-link text-dark"
                                   asp-controller="ManagerPersonalArea"
                                   asp-action="Index"
                                   asp-route-userId="@_userManager.GetUserId(User)">
                                    Личный кабинет
                                </a>
                            </li>
                        }
                        <li>
                            <a class="nav-link text-dark" asp-controller="Account"
                               asp-action="LogOff">Выйти</a></li>
                    </ul>
                </div>
            }
            else
            {
                <button data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                    <i class="bi bi-person text-warning user"></i>
                </button>
            }
        </div>
    </nav>
</header>

    <main role="main">
        @RenderBody()
    </main>


<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">Регистрация</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>

    </div>
    <div class="offcanvas-body">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        Регистрация
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        @await Html.PartialAsync("PartialViews/Account/RegisterPartialView", Model)
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Авторизация
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <form asp-action="Login" asp-controller="Account" method="post" asp-antiforgery="true" class="row g-3">
                            @await Html.PartialAsync("PartialViews/Account/LoginPartialView", Model)
                            <button class="btn btn-warning" type="submit">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MotoStore - <a asp-area="" asp-controller="Home" asp-action="Index" class="text-light">Домой</a>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://kit.fontawesome.com/e289fe644c.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", false)
<script type="text/javascript">
    var spinnerVisible = false;
    function showProgress() {
        if (!spinnerVisible) {
            $("div#spinner").fadeIn("fast");
            spinnerVisible = true;
        }
    };
    function hideProgress() {
        if (spinnerVisible) {
            var spinner = $("div#spinner");
            spinner.stop();
            spinner.fadeOut("fast");
            spinnerVisible = false;
        }
    };
</script>
</body>
</html>