MotoStore/Models/Position.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using MotoStore.Enums;

namespace MotoStore.Models
{
    public class Position
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string Id { get; set; }
        public DateTime CreationDateTime { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public NumberOfCycles NumberOfCycles { get; set; }
        public int EngineCapacity { get; set; }
        public string PathToImage { get; set; }
        public bool Deleted { get; set; }
        public decimal Price { get; set; }
    }
}

MotoStore/ViewModels/Positions/AllPositionsViewModel.cs
using System.Collections.Generic;

namespace MotoStore.ViewModels.Positions
{
    public class AllPositionsViewModel
    {
        public List<PositionShortInfoViewModel> Positions { get; set; }
        public PositionInfoViewModel PositionInfo { get; set; }
    }
}

MotoStore/ViewModels/Positions/CreatePositionViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using MotoStore.Enums;

namespace MotoStore.ViewModels.Positions
{
    public class CreatePositionViewModel
    {
        [DisplayName("Модель")]
        [Required(ErrorMessage = "Поле обязательно для ввода.")]
        [StringLength(25, MinimumLength = 3, ErrorMessage = "Минимальная длина: 5. Максимальная: 25")]
        public string Model { get; set; }
        
        [DisplayName("Производитель")]
        [Required(ErrorMessage = "Поле обязательно для ввода.")]
        [StringLength(25, MinimumLength = 2, ErrorMessage = "Минимальная длина: 5. Максимальная: 25")]
        public string Manufacturer { get; set; }
        
        [DisplayName("Число тактов")]
        [Required(ErrorMessage = "Поле обязательно для ввода.")]
        public NumberOfCycles NumberOfCycles { get; set; }
        
        [DisplayName("Объем двигателя в кубиках")]
        [Required(ErrorMessage = "Поле обязательно для ввода.")]
        [Range(50, 5000, ErrorMessage = "Некорректный объем")]
        public int EngineCapacity { get; set; }
        
        [Attributes.Validation.FileExtensions("jpg, png", ErrorMessage = "Некорректный формат файла")]
        [DisplayName("Загрузить изображение")]
        [Required(ErrorMessage = "Загрузите изображение")]
        public IFormFile Image { get; set; }
        
        [DisplayName("Стоимость")]
        [Required(ErrorMessage = "Поле обязательно для ввода.")]
        [Range(10000, 1000000, ErrorMessage = "Некорректное значение")]
        public decimal Price { get; set; }
    }
}

MotoStore/ViewModels/Positions/PositionInfoViewModel.cs
using MotoStore.Enums;

namespace MotoStore.ViewModels.Positions
{
    public class PositionInfoViewModel
    {
        public string Id { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public NumberOfCycles NumberOfCycles { get; set; }
        public int EngineCapacity { get; set; }
        public string PathToImage { get; set; }
        public decimal Price { get; set; }
    }
}

MotoStore/ViewModels/Positions/PositionShortInfoViewModel.cs
namespace MotoStore.ViewModels.Positions
{
    public class PositionShortInfoViewModel
    {
        public string Id { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string PathToImage { get; set; }
        public decimal Price { get; set; }
    }
}

MotoStore/Controllers/PositionController.cs
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using MotoStore.MapConfigurations;
using MotoStore.Services.Abstractions;
using MotoStore.ViewModels.Account;
using MotoStore.ViewModels.Layout;
using MotoStore.ViewModels.Positions;

namespace MotoStore.Controllers
{
    
    public class PositionController : Controller
    {
        private readonly ILogger<AccountController> _logger;
        private readonly IHostEnvironment _environment;
        private readonly IPositionService _positionService;
        

        public PositionController(
            IHostEnvironment environment,
            ILogger<AccountController> logger, 
            IPositionService positionService)
        {
            _environment = environment;
            _logger = logger;
            _positionService = positionService;
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Add(LayoutViewModel model)
        {
            //TODO: Добавить Try Catch и страницу ошибок.
            if (!ModelState.IsValid) return View(model);
            await _positionService.CreatePosition(model.CreatePositionViewModel, _environment);
            var positions = _positionService.GetPositions().ToList();
            return RedirectToAction("All", positions);

        }

        [HttpGet]
        public IActionResult All(LayoutViewModel model = null)
        {
            if (model!.AllPositionsViewModel is not null)
                return View(model);

            if (TempData["model"] is not null)
            {
                var test = JsonSerializer.Deserialize<LayoutViewModel>((string)TempData["model"]);
                return View(test);
            }
            
            //TODO: Сделать паггинацию 
            var positions = _positionService.GetPositions().ToList();
            var layoutViewModel = new LayoutViewModel
            {
                AllPositionsViewModel = new AllPositionsViewModel 
                    {Positions = positions.MapToShortInfoList()}
            };
            return View(layoutViewModel);
        }

        [HttpGet]
        public IActionResult Position(string id)
        {
            //TODO: Сделать паггинацию 
            var positions = _positionService.GetPositions().ToList();
            var positionViewModel = _positionService
                .GetPositionById(id)
                .MapToPositionInfoViewModel();
            
            var layoutModel = new LayoutViewModel
            {
                AllPositionsViewModel = new AllPositionsViewModel
                {
                    Positions = positions.MapToShortInfoList(),
                    PositionInfo = positionViewModel
                },
                LoginViewModel = new LoginViewModel(),
                RegisterViewModel = new RegisterViewModel(),
                CreatePositionViewModel = new CreatePositionViewModel()
            };
            TempData["model"] = JsonSerializer.Serialize(layoutModel);
            return RedirectToAction("All", "Position");
        }
    }
}

MotoStore/Controllers/SearchPositionController.cs
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MotoStore.Services.Abstractions;
using MotoStore.ViewModels.Layout;
using MotoStore.ViewModels.Positions;

namespace MotoStore.Controllers
{
    public class SearchPositionController  : Controller
    {
        private readonly ILogger<AccountController> _logger;
        private readonly IPositionService _positionService;

        public SearchPositionController(
            ILogger<AccountController> logger, 
            IPositionService positionService)
        {
            _logger = logger;
            _positionService = positionService;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string criterion)
        {
            _logger.LogInformation("{@Controller}.Search запрос: {@Criterion}", 
                typeof(SearchPositionController), criterion);
            var positions = await _positionService.GetPositionsByAnyCriterionAsync(criterion);
            LayoutViewModel layoutViewModel = new LayoutViewModel
            {
                AllPositionsViewModel = new AllPositionsViewModel
                {
                    Positions = positions
                }
            };
            TempData["model"] = JsonSerializer.Serialize(layoutViewModel);
            
            return RedirectToAction("All", "Position");
        }
    }
}

MotoStore/Views/Position/Add.cshtml
@model MotoStore.ViewModels.Layout.LayoutViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container">
    <div class="text-center my-5">
        <h2>Добавить позицию</h2>
    </div>
    <form asp-action="Add" 
          asp-controller="Position" 
          enctype="multipart/form-data" 
          method="post" 
          class="col-md-9 mx-auto" 
          asp-antiforgery="true">
        <div class="form-floating my-2">
            <input type="text" asp-for="@Model.CreatePositionViewModel.Manufacturer" class="form-control" id="inputManufacturer">
            <label for="inputManufacturer" class="form-label" asp-for="@Model.CreatePositionViewModel.Manufacturer"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.Manufacturer"></span>
        </div>
        <div class="form-floating my-2">
            <input type="text" asp-for="@Model.CreatePositionViewModel.Model" class="form-control" id="inputModel">
            <label for="inputModel" class="form-label" asp-for="@Model.CreatePositionViewModel.Model"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.Model"></span>
        </div>
        <div class="form-floating my-2">
            <input type="text" asp-for="@Model.CreatePositionViewModel.NumberOfCycles" class="form-control" id="inputNumberOfCycles">
            <label for="inputNumberOfCycles" class="form-label" asp-for="@Model.CreatePositionViewModel.NumberOfCycles"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.NumberOfCycles"></span>
        </div>
        <div class="form-floating my-2">
            <input type="text" asp-for="@Model.CreatePositionViewModel.EngineCapacity" class="form-control" id="inputEngineCapacity">
            <label for="inputEngineCapacity" class="form-label" asp-for="@Model.CreatePositionViewModel.EngineCapacity"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.EngineCapacity"></span>
        </div>
        <div class="form-floating my-2">
            <input type="file" asp-for="@Model.CreatePositionViewModel.Image" class="form-control" id="inputImage">
            <label for="inputImage" class="form-label" asp-for="@Model.CreatePositionViewModel.Image"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.Image"></span>
        </div>
        <div class="form-floating my-2">
            <input type="text" asp-for="@Model.CreatePositionViewModel.Price" class="form-control" id="inputPrice">
            <label for="inputPrice" class="form-label" asp-for="@Model.CreatePositionViewModel.Price"></label>
            <span class="text-warning" asp-validation-for="@Model.CreatePositionViewModel.Price"></span>
        </div>
        <button class="btn btn-warning my-1" type="submit">Добавить</button>
    </form>
</div>

MotoStore/Views/Position/All.cshtml
@model MotoStore.ViewModels.Layout.LayoutViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container">
    <div class="text-center my-5">
        <h2 class="сatalog-headding py-5">Каталог продукции</h2>
    </div>
    <form asp-controller="SearchPosition" asp-action="Search" method="get">
        <div class="input-group mb-3">
            <button class="btn btn-outline-warning" type="submit" id="button-addon1">Искать</button>
            <input name="criterion" 
                   type="text" class="form-control" 
                   placeholder="Поиск по моделям и производителям" 
                   aria-label="Example text with button addon" 
                   aria-describedby="button-addon1">
        </div>
    </form>
    <div class="row justify-content-evenly mb-5">
        @foreach (var position in Model.AllPositionsViewModel.Positions)
        {
            <div class="col-sx-12 col-sm-6 col-md-3 col-lg-2 my-2">
                <a asp-action="Position" asp-route-id="@position.Id">
                    <div class="card">
                        <img src="~/@position.PathToImage" class="card-img-top" alt="@position.Model">
                        <div class="card-body">
                            <p>@position.Manufacturer</p>
                            <p>@position.Model</p>
                            <p>@position.Price тенге</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>
<div class="container py-5">
    @await Html.PartialAsync("PartialViews/Position/PositionFullInfoPartialView", Model)
</div>